package ConnectionDataBase;
// Generated 14-Jun-2011 16:43:10 by Hibernate Tools 3.2.1.GA



/**
 * Auctionhistory generated by hbm2java
 */
public class Auctionhistory  implements java.io.Serializable {


     private int auctionid;
     private String bidder;
     private int offer;
     private long offertime;

    public Auctionhistory() {
    }

    public Auctionhistory(int auctionid, String bidder, int offer, long offertime) {
       this.auctionid = auctionid;
       this.bidder = bidder;
       this.offer = offer;
       this.offertime = offertime;
    }
   
    public int getAuctionid() {
        return this.auctionid;
    }
    
    public void setAuctionid(int auctionid) {
        this.auctionid = auctionid;
    }
    public String getBidder() {
        return this.bidder;
    }
    
    public void setBidder(String bidder) {
        this.bidder = bidder;
    }
    public int getOffer() {
        return this.offer;
    }
    
    public void setOffer(int offer) {
        this.offer = offer;
    }
    public long getOffertime() {
        return this.offertime;
    }
    
    public void setOffertime(long offertime) {
        this.offertime = offertime;
    }




}


