package ConnectionDataBase;
// Generated 13-Jun-2011 00:05:38 by Hibernate Tools 3.2.1.GA



/**
 * Events generated by hbm2java
 */
public class Events  implements java.io.Serializable {


     private String idname;
     private int barnight;
     private int facebookblocked;
     private int girlsarrival;
     private int governmentgrant;
     private int haskellconference;
     private int highranking;
     private int labshacking;
     private int labsinfire;
     private int lecturerpromotion;
     private int macchickenpromotion;
     private int malice;
     private int nobelprice;
     private int outofchicken;
     private int paperleak;
     private int phdpromotion;
     private int pintoscw;
     private int privatecompanygrant;
     private int pubdemolished;
     private int trescomiracle;
     private int trescotragedy;
     private int unionparty;

    public Events() {
    }

    public Events(String idname, int barnight, int facebookblocked, int girlsarrival, int governmentgrant, int haskellconference, int highranking, int labshacking, int labsinfire, int lecturerpromotion, int macchickenpromotion, int malice, int nobelprice, int outofchicken, int paperleak, int phdpromotion, int pintoscw, int privatecompanygrant, int pubdemolished, int trescomiracle, int trescotragedy, int unionparty) {
       this.idname = idname;
       this.barnight = barnight;
       this.facebookblocked = facebookblocked;
       this.girlsarrival = girlsarrival;
       this.governmentgrant = governmentgrant;
       this.haskellconference = haskellconference;
       this.highranking = highranking;
       this.labshacking = labshacking;
       this.labsinfire = labsinfire;
       this.lecturerpromotion = lecturerpromotion;
       this.macchickenpromotion = macchickenpromotion;
       this.malice = malice;
       this.nobelprice = nobelprice;
       this.outofchicken = outofchicken;
       this.paperleak = paperleak;
       this.phdpromotion = phdpromotion;
       this.pintoscw = pintoscw;
       this.privatecompanygrant = privatecompanygrant;
       this.pubdemolished = pubdemolished;
       this.trescomiracle = trescomiracle;
       this.trescotragedy = trescotragedy;
       this.unionparty = unionparty;
    }
   
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }
    public int getBarnight() {
        return this.barnight;
    }
    
    public void setBarnight(int barnight) {
        this.barnight = barnight;
    }
    public int getFacebookblocked() {
        return this.facebookblocked;
    }
    
    public void setFacebookblocked(int facebookblocked) {
        this.facebookblocked = facebookblocked;
    }
    public int getGirlsarrival() {
        return this.girlsarrival;
    }
    
    public void setGirlsarrival(int girlsarrival) {
        this.girlsarrival = girlsarrival;
    }
    public int getGovernmentgrant() {
        return this.governmentgrant;
    }
    
    public void setGovernmentgrant(int governmentgrant) {
        this.governmentgrant = governmentgrant;
    }
    public int getHaskellconference() {
        return this.haskellconference;
    }
    
    public void setHaskellconference(int haskellconference) {
        this.haskellconference = haskellconference;
    }
    public int getHighranking() {
        return this.highranking;
    }
    
    public void setHighranking(int highranking) {
        this.highranking = highranking;
    }
    public int getLabshacking() {
        return this.labshacking;
    }
    
    public void setLabshacking(int labshacking) {
        this.labshacking = labshacking;
    }
    public int getLabsinfire() {
        return this.labsinfire;
    }
    
    public void setLabsinfire(int labsinfire) {
        this.labsinfire = labsinfire;
    }
    public int getLecturerpromotion() {
        return this.lecturerpromotion;
    }
    
    public void setLecturerpromotion(int lecturerpromotion) {
        this.lecturerpromotion = lecturerpromotion;
    }
    public int getMacchickenpromotion() {
        return this.macchickenpromotion;
    }
    
    public void setMacchickenpromotion(int macchickenpromotion) {
        this.macchickenpromotion = macchickenpromotion;
    }
    public int getMalice() {
        return this.malice;
    }
    
    public void setMalice(int malice) {
        this.malice = malice;
    }
    public int getNobelprice() {
        return this.nobelprice;
    }
    
    public void setNobelprice(int nobelprice) {
        this.nobelprice = nobelprice;
    }
    public int getOutofchicken() {
        return this.outofchicken;
    }
    
    public void setOutofchicken(int outofchicken) {
        this.outofchicken = outofchicken;
    }
    public int getPaperleak() {
        return this.paperleak;
    }
    
    public void setPaperleak(int paperleak) {
        this.paperleak = paperleak;
    }
    public int getPhdpromotion() {
        return this.phdpromotion;
    }
    
    public void setPhdpromotion(int phdpromotion) {
        this.phdpromotion = phdpromotion;
    }
    public int getPintoscw() {
        return this.pintoscw;
    }
    
    public void setPintoscw(int pintoscw) {
        this.pintoscw = pintoscw;
    }
    public int getPrivatecompanygrant() {
        return this.privatecompanygrant;
    }
    
    public void setPrivatecompanygrant(int privatecompanygrant) {
        this.privatecompanygrant = privatecompanygrant;
    }
    public int getPubdemolished() {
        return this.pubdemolished;
    }
    
    public void setPubdemolished(int pubdemolished) {
        this.pubdemolished = pubdemolished;
    }
    public int getTrescomiracle() {
        return this.trescomiracle;
    }
    
    public void setTrescomiracle(int trescomiracle) {
        this.trescomiracle = trescomiracle;
    }
    public int getTrescotragedy() {
        return this.trescotragedy;
    }
    
    public void setTrescotragedy(int trescotragedy) {
        this.trescotragedy = trescotragedy;
    }
    public int getUnionparty() {
        return this.unionparty;
    }
    
    public void setUnionparty(int unionparty) {
        this.unionparty = unionparty;
    }




}


