package ConnectionDataBase;
// Generated 11-Jun-2011 18:04:56 by Hibernate Tools 3.2.1.GA



/**
 * Extrastats generated by hbm2java
 */
public class Extrastats  implements java.io.Serializable {


     private String idname;
     private int satisfaction;
     private int starvation;
     private int alcoholizm;

    public Extrastats() {
    }

    public Extrastats(String idname, int satisfaction, int starvation, int alcoholizm) {
       this.idname = idname;
       this.satisfaction = satisfaction;
       this.starvation = starvation;
       this.alcoholizm = alcoholizm;
    }
   
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }
    public int getSatisfaction() {
        return this.satisfaction;
    }
    
    public void setSatisfaction(int satisfaction) {
        this.satisfaction = satisfaction;
    }
    public int getStarvation() {
        return this.starvation;
    }
    
    public void setStarvation(int starvation) {
        this.starvation = starvation;
    }
    public int getAlcoholizm() {
        return this.alcoholizm;
    }
    
    public void setAlcoholizm(int alcoholizm) {
        this.alcoholizm = alcoholizm;
    }




}


