package ConnectionDataBase;
// Generated 18-Jun-2011 14:11:42 by Hibernate Tools 3.2.1.GA



/**
 * Lecturers generated by hbm2java
 */
public class Lecturers  implements java.io.Serializable {


     private int lecturerid;
     private String lecturername;
     private Integer price;
     private Boolean usable;

    public Lecturers() {
    }

	
    public Lecturers(int lecturerid, String lecturername) {
        this.lecturerid = lecturerid;
        this.lecturername = lecturername;
    }
    public Lecturers(int lecturerid, String lecturername, Integer price, Boolean usable) {
       this.lecturerid = lecturerid;
       this.lecturername = lecturername;
       this.price = price;
       this.usable = usable;
    }
   
    public int getLecturerid() {
        return this.lecturerid;
    }
    
    public void setLecturerid(int lecturerid) {
        this.lecturerid = lecturerid;
    }
    public String getLecturername() {
        return this.lecturername;
    }
    
    public void setLecturername(String lecturername) {
        this.lecturername = lecturername;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Boolean getUsable() {
        return this.usable;
    }
    
    public void setUsable(Boolean usable) {
        this.usable = usable;
    }




}


