package ConnectionDataBase;
// Generated 08-Jun-2011 10:04:00 by Hibernate Tools 3.2.1.GA



/**
 * Lecturersspecializations generated by hbm2java
 */
public class Lecturersspecializations  implements java.io.Serializable {


     private LecturersspecializationsId id;
     private Integer boost;

    public Lecturersspecializations() {
    }


    public Lecturersspecializations(LecturersspecializationsId id) {
        this.id = id;
    }
    public Lecturersspecializations(LecturersspecializationsId id, Integer boost) {
       this.id = id;
       this.boost = boost;
    }

    public Lecturersspecializations(String name , String specialization, Integer boost) {
        LecturersspecializationsId id
                = new LecturersspecializationsId(name, specialization);
        this.id = id;
        this.boost = boost;
    }

    public LecturersspecializationsId getId() {
        return this.id;
    }

    public void setId(LecturersspecializationsId id) {
        this.id = id;
    }

    public String getLecturername() {
        return id.getLecturername();
    }

    public String getSpecialization() {
        return id.getSpecialization();
    }

    public void setLecturername(String name) {
        id.setLecturername(name);
    }

    public void setSpecialization(String specialization) {
        id.setSpecialization(specialization);
    }

    public Integer getBoost() {
        return this.boost;
    }

    public void setBoost(Integer boost) {
        this.boost = boost;
    }




}