package ConnectionDataBase;
// Generated 08-Jun-2011 16:56:09 by Hibernate Tools 3.2.1.GA



/**
 * Lecturersowned generated by hbm2java
 */
public class Lecturersowned  implements java.io.Serializable {


     private String lecturername;
     private String idname;

    public Lecturersowned() {
    }

	
    public Lecturersowned(String lecturername) {
        this.lecturername = lecturername;
    }
    public Lecturersowned(String lecturername, String idname) {
       this.lecturername = lecturername;
       this.idname = idname;
    }
   
    public String getLecturername() {
        return this.lecturername;
    }
    
    public void setLecturername(String lecturername) {
        this.lecturername = lecturername;
    }
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }




}


