package ConnectionDataBase;
// Generated 06-Jun-2011 22:06:30 by Hibernate Tools 3.2.1.GA



/**
 * Lecturersspecializations generated by hbm2java
 */
public class Lecturersspecializations  implements java.io.Serializable {


     private String lecturername;
     private String specialization;
     private Integer boost;

    public Lecturersspecializations() {
    }

	
    public Lecturersspecializations(String lecturername) {
        this.lecturername = lecturername;
    }
    public Lecturersspecializations(String lecturername, String specialization, Integer boost) {
       this.lecturername = lecturername;
       this.specialization = specialization;
       this.boost = boost;
    }
   
    public String getLecturername() {
        return this.lecturername;
    }
    
    public void setLecturername(String lecturername) {
        this.lecturername = lecturername;
    }
    public String getSpecialization() {
        return this.specialization;
    }
    
    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }
    public Integer getBoost() {
        return this.boost;
    }
    
    public void setBoost(Integer boost) {
        this.boost = boost;
    }




}


