package ConnectionDataBase;
// Generated 06-Jun-2011 22:06:30 by Hibernate Tools 3.2.1.GA



/**
 * Players generated by hbm2java
 */
public class Players  implements java.io.Serializable {


     private String idname;
     private String password;
     private String email;
     private Boolean loggedin;

    public Players() {
    }

	
    public Players(String idname, String password, String email) {
        this.idname = idname;
        this.password = password;
        this.email = email;
    }
    public Players(String idname, String password, String email, Boolean loggedin) {
       this.idname = idname;
       this.password = password;
       this.email = email;
       this.loggedin = loggedin;
    }
   
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getLoggedin() {
        return this.loggedin;
    }
    
    public void setLoggedin(Boolean loggedin) {
        this.loggedin = loggedin;
    }




}


