package ConnectionDataBase;
// Generated 09-Jun-2011 17:14:20 by Hibernate Tools 3.2.1.GA



/**
 * PlayerresearchId generated by hbm2java
 */
public class PlayerresearchId  implements java.io.Serializable {


     private String idname;
     private int researchid;

    public PlayerresearchId() {
    }

    public PlayerresearchId(String idname, int researchid) {
       this.idname = idname;
       this.researchid = researchid;
    }
   
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }
    public int getResearchid() {
        return this.researchid;
    }
    
    public void setResearchid(int researchid) {
        this.researchid = researchid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlayerresearchId) ) return false;
		 PlayerresearchId castOther = ( PlayerresearchId ) other; 
         
		 return ( (this.getIdname()==castOther.getIdname()) || ( this.getIdname()!=null && castOther.getIdname()!=null && this.getIdname().equals(castOther.getIdname()) ) )
 && (this.getResearchid()==castOther.getResearchid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdname() == null ? 0 : this.getIdname().hashCode() );
         result = 37 * result + this.getResearchid();
         return result;
   }   


}


