package ConnectionDataBase;
// Generated 09-Jun-2011 15:21:02 by Hibernate Tools 3.2.1.GA



/**
 * Playerresources generated by hbm2java
 */
public class Playerresources  implements java.io.Serializable {


     private String idname;
     private Integer money;
     private Integer researchpoints;
     private Integer undergraduatesnumber;
     private Integer phdsnumber;

    public Playerresources() {
    }

	
    public Playerresources(String idname) {
        this.idname = idname;
    }
    public Playerresources(String idname, Integer money, Integer researchpoints, Integer undergraduatesnumber, Integer phdsnumber) {
       this.idname = idname;
       this.money = money;
       this.researchpoints = researchpoints;
       this.undergraduatesnumber = undergraduatesnumber;
       this.phdsnumber = phdsnumber;
    }
   
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }
    public Integer getMoney() {
        return this.money;
    }
    
    public void setMoney(Integer money) {
        this.money = money;
    }
    public Integer getResearchpoints() {
        return this.researchpoints;
    }
    
    public void setResearchpoints(Integer researchpoints) {
        this.researchpoints = researchpoints;
    }
    public Integer getUndergraduatesnumber() {
        return this.undergraduatesnumber;
    }
    
    public void setUndergraduatesnumber(Integer undergraduatesnumber) {
        this.undergraduatesnumber = undergraduatesnumber;
    }
    public Integer getPhdsnumber() {
        return this.phdsnumber;
    }
    
    public void setPhdsnumber(Integer phdsnumber) {
        this.phdsnumber = phdsnumber;
    }




}


