package ConnectionDataBase;
// Generated 11-Jun-2011 15:50:27 by Hibernate Tools 3.2.1.GA



/**
 * Playerresearch generated by hbm2java
 */
public class Playerresearch  implements java.io.Serializable {


     private PlayerresearchId id;

    public Playerresearch() {
    }

    public Playerresearch(PlayerresearchId id) {
       this.id = id;
    }
   
    public PlayerresearchId getId() {
        return this.id;
    }
    
    public void setId(PlayerresearchId id) {
        this.id = id;
    }




}


