package ConnectionDataBase;
// Generated 06-Jun-2011 13:02:17 by Hibernate Tools 3.2.1.GA



/**
 * Playerresources generated by hbm2java
 */
public class Playerresources  implements java.io.Serializable {


     private String idname;
     private Integer money;
     private Integer researchpoints;
     private Integer undegraduatesnumber;
     private Integer phdsnumber;

    public Playerresources() {
    }

	
    public Playerresources(String idname) {
        this.idname = idname;
    }
    public Playerresources(String idname, Integer money, Integer researchpoints, Integer undegraduatesnumber, Integer phdsnumber) {
       this.idname = idname;
       this.money = money;
       this.researchpoints = researchpoints;
       this.undegraduatesnumber = undegraduatesnumber;
       this.phdsnumber = phdsnumber;
    }
   
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }
    public Integer getMoney() {
        return this.money;
    }
    
    public void setMoney(Integer money) {
        this.money = money;
    }
    public Integer getResearchpoints() {
        return this.researchpoints;
    }
    
    public void setResearchpoints(Integer researchpoints) {
        this.researchpoints = researchpoints;
    }
    public Integer getUndegraduatesnumber() {
        return this.undegraduatesnumber;
    }
    
    public void setUndegraduatesnumber(Integer undegraduatesnumber) {
        this.undegraduatesnumber = undegraduatesnumber;
    }
    public Integer getPhdsnumber() {
        return this.phdsnumber;
    }
    
    public void setPhdsnumber(Integer phdsnumber) {
        this.phdsnumber = phdsnumber;
    }




}


