package ConnectionDataBase;
// Generated 06-Jun-2011 22:44:46 by Hibernate Tools 3.2.1.GA



/**
 * ResearchId generated by hbm2java
 */
public class ResearchId  implements java.io.Serializable {


     private String idname;
     private String title;

    public ResearchId() {
    }

    public ResearchId(String idname, String title) {
       this.idname = idname;
       this.title = title;
    }
   
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ResearchId) ) return false;
		 ResearchId castOther = ( ResearchId ) other; 
         
		 return ( (this.getIdname()==castOther.getIdname()) || ( this.getIdname()!=null && castOther.getIdname()!=null && this.getIdname().equals(castOther.getIdname()) ) )
 && ( (this.getTitle()==castOther.getTitle()) || ( this.getTitle()!=null && castOther.getTitle()!=null && this.getTitle().equals(castOther.getTitle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdname() == null ? 0 : this.getIdname().hashCode() );
         result = 37 * result + ( getTitle() == null ? 0 : this.getTitle().hashCode() );
         return result;
   }   


}


