package ConnectionDataBase;
// Generated 09-Jun-2011 16:59:47 by Hibernate Tools 3.2.1.GA



/**
 * Researchdependencies generated by hbm2java
 */
public class Researchdependencies  implements java.io.Serializable {


     private ResearchdependenciesId id;

    public Researchdependencies() {
    }

    public Researchdependencies(ResearchdependenciesId id) {
       this.id = id;
    }
   
    public ResearchdependenciesId getId() {
        return this.id;
    }
    
    public void setId(ResearchdependenciesId id) {
        this.id = id;
    }




}


