package ConnectionDataBase;
// Generated 10-Jun-2011 13:45:11 by Hibernate Tools 3.2.1.GA



/**
 * ResearchId generated by hbm2java
 */
public class ResearchId  implements java.io.Serializable {


     private String idname;
     private int researchid;

    public ResearchId() {
    }

    public ResearchId(String idname, int researchid) {
       this.idname = idname;
       this.researchid = researchid;
    }
   
    public String getIdname() {
        return this.idname;
    }
    
    public void setIdname(String idname) {
        this.idname = idname;
    }
    public int getResearchid() {
        return this.researchid;
    }
    
    public void setResearchid(int researchid) {
        this.researchid = researchid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ResearchId) ) return false;
		 ResearchId castOther = ( ResearchId ) other; 
         
		 return ( (this.getIdname()==castOther.getIdname()) || ( this.getIdname()!=null && castOther.getIdname()!=null && this.getIdname().equals(castOther.getIdname()) ) )
 && (this.getResearchid()==castOther.getResearchid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdname() == null ? 0 : this.getIdname().hashCode() );
         result = 37 * result + this.getResearchid();
         return result;
   }   


}


