package ConnectionDataBase;
// Generated 10-Jun-2011 13:45:11 by Hibernate Tools 3.2.1.GA



/**
 * Researchcatalogue generated by hbm2java
 */
public class Researchcatalogue  implements java.io.Serializable {


     private String researchname;
     private String researchdescription;
     private int researchid;
     private int subjectid;
     private Integer researchpoints;

    public Researchcatalogue() {
    }

	
    public Researchcatalogue(String researchname, String researchdescription, int researchid, int subjectid) {
        this.researchname = researchname;
        this.researchdescription = researchdescription;
        this.researchid = researchid;
        this.subjectid = subjectid;
    }
    public Researchcatalogue(String researchname, String researchdescription, int researchid, int subjectid, Integer researchpoints) {
       this.researchname = researchname;
       this.researchdescription = researchdescription;
       this.researchid = researchid;
       this.subjectid = subjectid;
       this.researchpoints = researchpoints;
    }
   
    public String getResearchname() {
        return this.researchname;
    }
    
    public void setResearchname(String researchname) {
        this.researchname = researchname;
    }
    public String getResearchdescription() {
        return this.researchdescription;
    }
    
    public void setResearchdescription(String researchdescription) {
        this.researchdescription = researchdescription;
    }
    public int getResearchid() {
        return this.researchid;
    }
    
    public void setResearchid(int researchid) {
        this.researchid = researchid;
    }
    public int getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(int subjectid) {
        this.subjectid = subjectid;
    }
    public Integer getResearchpoints() {
        return this.researchpoints;
    }
    
    public void setResearchpoints(Integer researchpoints) {
        this.researchpoints = researchpoints;
    }




}


