package ConnectionDataBase;
// Generated 09-Jun-2011 22:33:22 by Hibernate Tools 3.2.1.GA



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private String subjectname;
     private int subjectid;

    public Subject() {
    }

    public Subject(String subjectname, int subjectid) {
       this.subjectname = subjectname;
       this.subjectid = subjectid;
    }
   
    public String getSubjectname() {
        return this.subjectname;
    }
    
    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname;
    }
    public int getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(int subjectid) {
        this.subjectid = subjectid;
    }




}


