package ConnectionDataBase;
// Generated 14-Jun-2011 16:43:10 by Hibernate Tools 3.2.1.GA



/**
 * Tests generated by hbm2java
 */
public class Tests  implements java.io.Serializable {


     private int id;
     private String tekst;

    public Tests() {
    }

    public Tests(int id, String tekst) {
       this.id = id;
       this.tekst = tekst;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }




}


